<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>css</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*(?!\*)|\{\s*($|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Better CSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-charset</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#property-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#selector</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>at-charset</key>
		<dict>
			<key>begin</key>
			<string>(@)(charset)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.keyword.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>@charset</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.charset.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.css</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.css</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(")[-_+:.0-9a-zA-Z]*(")</string>
					<key>name</key>
					<string>string.quoted.double.css</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^"].*?</string>
					<key>name</key>
					<string>invalid.illegal.bad-charset.css</string>
				</dict>
			</array>
		</dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.css</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.css</string>
	<key>uuid</key>
	<string>4BA5F7E1-8D36-4634-8D88-86C0157A8E54</string>
</dict>
</plist>
