<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Better CSS</string>
    <key>scopeName</key>
    <string>source.css</string>
    <key>fileTypes</key>
    <array>
      <string>css</string>
    </array>
    <key>uuid</key>
    <string>5E1320A0-3857-4AB6-8F5F-F7459F347CCF</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment-block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-charset</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-color-profile</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-counter-style</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-keyframes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-namespace</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#at-property</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#property-list</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#selector</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>arbitrary-repetition</key>
      <dict>
        <key>match</key>
        <string>\s*(?:(,))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.arbitrary-repetition.css</string>
          </dict>
        </dict>
      </dict>
      <key>at-charset</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.charset.css</string>
        <key>begin</key>
        <string>(@)(charset)\s</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.at-rule.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.css</string>
            <key>match</key>
            <string>(")[-_+:.0-9a-zA-Z]*(")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.css</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.bad-charset.css</string>
            <key>match</key>
            <string>[^"].*?</string>
          </dict>
        </array>
      </dict>
      <key>at-color-profile</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.color-profile.css</string>
        <key>begin</key>
        <string>(?=\s*@color-profile\b)</string>
        <key>end</key>
        <string>\s*(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\s*((@)color-profile)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.at-rule.color-profile.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.css</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.color-profile.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\s*(?=\{)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>name</key>
                <string>support.constant.color-profile.css</string>
                <key>match</key>
                <string>device-cmyk</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#custom-property-name</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#rendering-intent-descriptor</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#src-descriptor</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>at-counter-style</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.counter-style.css</string>
        <key>begin</key>
        <string>((@)counter-style)\s+(?:(disclosure-open|disclosure-closed|disc|decimal|square|circle)|(--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*))\s*(?=\{|$)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.at-rule.counter-style.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.counter-style-name.css</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.style-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#system-descriptor</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>at-import</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.import.css</string>
        <key>begin</key>
        <string>(@)(import)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.at-rule.import.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-layer</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-supports</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-url</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.context.resource.css</string>
            <key>match</key>
            <string>\blayer\s*(?=;)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#media-condition</string>
          </dict>
        </array>
      </dict>
      <key>at-keyframes</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.keyframes.css</string>
        <key>begin</key>
        <string>(@)keyframes</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.at-rule.keyframe.css</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.other.keyframe-offset.css</string>
                <key>match</key>
                <string>\b(?:from|to)\b</string>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.keyframe-selector.css</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.other.keyframe-offset.percentage.css</string>
                <key>include</key>
                <string>#percentage-type</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#arbitrary-repetition</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=[^{;])</string>
            <key>end</key>
            <string>(?=\{)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.parameter.animation-name.css</string>
                <key>include</key>
                <string>#ident-token</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>at-namespace</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.namespace.css</string>
        <key>begin</key>
        <string>(@)(namespace)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.at-rule.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-url</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-src</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter.namespace-prefix.css</string>
            <key>match</key>
            <string>--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
          </dict>
        </array>
      </dict>
      <key>at-property</key>
      <dict>
        <key>name</key>
        <string>meta.at-rule.property.css</string>
        <key>begin</key>
        <string>(@)property</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.at-rule.css</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter.property-name.css</string>
            <key>match</key>
            <string>--(?:(?:[a-zA-Z_\d-]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#inherits-descriptor</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#initial-value-descriptor</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#syntax-descriptor</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment-block</key>
      <dict>
        <key>name</key>
        <string>comment.block.css</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.css</string>
          </dict>
        </dict>
      </dict>
      <key>custom-property-name</key>
      <dict>
        <key>name</key>
        <string>variable.parameter.custom-property-name.css</string>
        <key>match</key>
        <string>--(?:(?:[a-zA-Z_\d-]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
      </dict>
      <key>dimension</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#length-type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#percentage-type</string>
          </dict>
        </array>
      </dict>
      <key>function-layer</key>
      <dict>
        <key>comment</key>
        <string>layer()</string>
        <key>name</key>
        <string>meta.function-call.layer.css</string>
        <key>begin</key>
        <string>\b(layer)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.layer.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.begin.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.constant.layer-name.css</string>
            <key>match</key>
            <string>(?'ident'--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*)(?:(\.)\g'ident')*</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.dot.css</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>function-src</key>
      <dict>
        <key>comment</key>
        <string>url("quoted" modifier)</string>
        <key>name</key>
        <string>meta.function-call.src.css</string>
        <key>begin</key>
        <string>\b(src)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.src.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.begin.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter.url-modifier.css</string>
            <key>match</key>
            <string>--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
          </dict>
        </array>
      </dict>
      <key>function-supports</key>
      <dict>
        <key>comment</key>
        <string>supports()</string>
        <key>name</key>
        <string>meta.function-call.supports.css</string>
        <key>begin</key>
        <string>\b(supports)(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.supports.css</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.begin.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.group.end.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#supports-condition</string>
          </dict>
        </array>
      </dict>
      <key>function-url</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>url("quoted" modifier)</string>
            <key>name</key>
            <string>meta.function-call.url.css</string>
            <key>begin</key>
            <string>\b(url)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.url.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.end.css</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
              <dict>
                <key>match</key>
                <string>--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
                <key>name</key>
                <string>variable.parameter.url-modifier.css</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>url(unquoted)</string>
            <key>name</key>
            <string>meta.function-call.css</string>
            <key>match</key>
            <string>\b(url)(\()((?:(?:[\s\R]+)*?))((?:(?:[^"'\(\)]|\S|[^\x{0000}-\x{0008}\x{000B}\x{000E}-\x{001F}\x{007F}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*?)((?:(?:[\s\R]+)*?))(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.url.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.begin.css</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.url.css</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.end.css</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>ident-token</key>
      <dict>
        <key>match</key>
        <string>--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
      </dict>
      <key>important</key>
      <dict>
        <key>name</key>
        <string>keyword.other.important.css</string>
        <key>match</key>
        <string>(\!)\s*important</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.css</string>
          </dict>
        </dict>
      </dict>
      <key>inherits-descriptor</key>
      <dict>
        <key>begin</key>
        <string>\binherits\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)|(?=\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.rule.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>contentName</key>
            <string>meta.property-value.css</string>
            <key>begin</key>
            <string>(:)(?=(?:(?:[\s\R]+)*?)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*(;)|(?=[})]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>name</key>
                <string>support.constant.property-value.css</string>
                <key>match</key>
                <string>true|false</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>initial-value-descriptor</key>
      <dict>
        <key>begin</key>
        <string>\binitial-value\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)|(?=\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.rule.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>contentName</key>
            <string>meta.property-value.css</string>
            <key>begin</key>
            <string>(:)(?=(?:(?:[\s\R]+)*?)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*(;)|(?=[})]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#property-value</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>integer-type</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.css</string>
        <key>match</key>
        <string>(?:[-+]?\d+)</string>
      </dict>
      <key>length-type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.css</string>
            <key>match</key>
            <string>((?:[-+]?(?:\d+\.\d+|\d+|\.\d+)(?:[eE][-+]?\d+)?))(ex|cap|ch|i[cn]|r?em|r?lh|[sld]?v(?:[whib]|min|max)|[cm]m|Q|p[ctx])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.unit.length.css</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>media-condition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.parens.support-condition.css</string>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.end.css</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.css</string>
            <key>match</key>
            <string>\b(and|or|not)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#media-feature</string>
          </dict>
        </array>
      </dict>
      <key>media-feature</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.constant.media-feature.css</string>
            <key>begin</key>
            <string>(--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*)(?:(?:[\s\R]+)*?)(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.media-feature.name.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>name</key>
                <string>constant.numeric.media-feature.css</string>
                <key>match</key>
                <string>(?:[-+]?(?:\d+\.\d+|\d+|\.\d+)(?:[eE][-+]?\d+)?)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>percentage-type</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.css</string>
        <key>match</key>
        <string>(?:[-+]?(?:\d+\.\d+|\d+|\.\d+)(?:[eE][-+]?\d+)?)(%)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.unit.percentage.css</string>
          </dict>
        </dict>
      </dict>
      <key>property-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?=(?=[^;]*)\{)</string>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.end.css</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#rule-list</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>property-value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>global values</string>
            <key>name</key>
            <string>support.constant.property-value.css</string>
            <key>match</key>
            <string>\b(?:inherit|initial|revert-layer|revert|unset)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>common values</string>
            <key>name</key>
            <string>support.constant.property-value.css</string>
            <key>match</key>
            <string>\b(?:auto|none|normal)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#important</string>
          </dict>
        </array>
      </dict>
      <key>rendering-intent-descriptor</key>
      <dict>
        <key>begin</key>
        <string>\brendering-intent\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)|(?=\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.rule.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>contentName</key>
            <string>meta.property-value.css</string>
            <key>begin</key>
            <string>(:)(?=(?:(?:[\s\R]+)*?)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*(;)|(?=[})]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>name</key>
                <string>support.constant.property-value.css</string>
                <key>match</key>
                <string>auto|perceptual|relative-colorimetric|saturation|absolute-colorimetric</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>rule-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.property-list.css</string>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\s*(;)|(?=[})])</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.terminator.rule.css</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#rule-list-body</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>src-descriptor</key>
      <dict>
        <key>begin</key>
        <string>\bsrc\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)|(?=\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.rule.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>contentName</key>
            <string>meta.property-value.css</string>
            <key>begin</key>
            <string>(:)(?=(?:(?:[\s\R]+)*?)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*(;)|(?=[})]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function-src</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#function-url</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>"double quoted string"</string>
            <key>name</key>
            <string>string.quoted.double.css</string>
            <key>match</key>
            <string>(")(?:(?:[^"\\]|\N)|(?:(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))|\\\n)*?(")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.css</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>'single quoted string'</string>
            <key>name</key>
            <string>string.quoted.single.css</string>
            <key>match</key>
            <string>(')(?:(?:[^"\\]|\N)|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))|\\\n)*?(\1)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.css</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.css</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>supports-condition</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.parens.support-condition.css</string>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.begin.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.group.end.css</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.supports-condition.css</string>
            <key>match</key>
            <string>\b(and|or|not)\b</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.css</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>syntax-descriptor</key>
      <dict>
        <key>begin</key>
        <string>\bsyntax\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)|(?=\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.rule.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>contentName</key>
            <string>meta.property-value.css</string>
            <key>begin</key>
            <string>(:)(?=(?:(?:[\s\R]+)*?)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*(;)|(?=[})]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>system-descriptor</key>
      <dict>
        <key>begin</key>
        <string>\bsystem\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(;)|(?=\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.rule.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment-block</string>
          </dict>
          <dict>
            <key>contentName</key>
            <string>meta.property-value.css</string>
            <key>begin</key>
            <string>(:)(?=(?:(?:[\s\R]+)*?)*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.css</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*(;)|(?=[})]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#integer-type</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#property-value</string>
              </dict>
              <dict>
                <key>name</key>
                <string>support.constant.property-value.css</string>
                <key>match</key>
                <string>cyclic|numeric|alphabetic|symbolic|additive|fixed|extends</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.parameter.style-name.css</string>
                <key>match</key>
                <string>--|(?:-?(?:(?:[a-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R]))))(?:(?:[-\da-zA-Z_]|[\x{00B7}\x{00C0}-\x{00D6}\x{00D8}-\x{00F6}\x{00F8}-\x{037D}\x{037F}-\x{1FFF}\x{200C}\x{200D}\x{203F}\x{2040}\x{2070}-\x{218F}\x{2C00}-\x{2FEF}\x{3001}-\x{D7FF}\x{F900}-\x{FDCF}\x{FDF0}-\x{FFFD}\x{10000}-\x{EFFFF}])|(?:\\(?:\N|[[:^xdigit:]]|[[:xdigit:]]{1,6}[\s\R])))*</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>foldingStartMarker</key>
    <string>/\*\*(?!\*)|\{\s*($|/\*(?!.*?\*/.*\S))</string>
    <key>foldingStopMarker</key>
    <string>(?&lt;!\*)\*\*/|^\s*\}</string>
    <key>keyEquivalent</key>
    <string>^~L</string>
  </dict>
</plist>